# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GHbWohY1WOY4ObaQl0qEhJQsuBsm6Cma
"""

#NAME：Tan Junjie
"""
Assignment One - Tan Junjie
Contains two tasks:
1. Terminal-based Calculator
2. Interactive Keyword Bot
"""

# ============================================================
# Task 1: Terminal-based Calculator
# ============================================================

def get_number(prompt: str) -> float:
    """Prompt until a valid number is entered."""
    while True:
        try:
            value = input(prompt).strip()
            return float(value)
        except ValueError:
            print("  Invalid input. Please enter a number (e.g. 5 or 3.14).")


def get_operator() -> str:
    """Prompt until a valid operator is chosen."""
    valid = {"+", "-", "*", "/"}
    while True:
        op = input("Choose operator (+, -, *, /): ").strip()
        if op in valid:
            return op
        print("  Invalid operator. Please enter one of: +  -  *  /")


def calculate(a: float, b: float, op: str) -> float | None:
    """Perform the calculation. Returns None on division by zero."""
    if op == "+":
        return a + b
    if op == "-":
        return a - b
    if op == "*":
        return a * b
    if op == "/":
        if b == 0:
            return None
        return a / b
    return None


def format_number(n: float) -> str:
    """Show integers without trailing .0 for cleaner output."""
    if n == int(n):
        return str(int(n))
    return str(n)


def run_calculator() -> None:
    print("\n" + "=" * 40)
    print("       Simple Terminal Calculator")
    print("=" * 40)

    while True:
        print()
        # 1. Prompt for first number
        num1 = get_number("Enter first number: ")

        # 2. Prompt for second number
        num2 = get_number("Enter second number: ")

        # 3. Choose operator
        operator = get_operator()

        # Perform calculation
        result = calculate(num1, num2, operator)

        # 4. Display clear math result
        print()
        if result is None:
            print("Error: Division by zero is not allowed.")
        else:
            a = format_number(num1)
            b = format_number(num2)
            r = format_number(result)
            print(f"Result:  {a} {operator} {b} = {r}")

        # Ask to continue
        print()
        again = input("Do another calculation? (y/n): ").strip().lower()
        if again not in ("y", "yes"):
            print("\nReturning to main menu...")
            break


# ============================================================
# Task 2: Interactive Keyword Bot
# ============================================================

def run_bot() -> None:
    print("\n" + "=" * 45)
    print("       Interactive Keyword Bot")
    print("Type your question (or 'quit' to exit)")
    print("=" * 45)

    while True:
        # 1. Use input() to receive questions
        user_input = input("\nYou: ").strip().lower()

        if user_input in ("quit", "exit", "bye"):
            print("Bot: Goodbye! Returning to main menu...")
            break

        # 2. Use if/elif/else for logic
        # 3 & 4. Support the required keywords: hello, python, jetson, ai, name
        if "hello" in user_input:
            print("Bot: Hello! Nice to meet you.")

        elif "python" in user_input:
            print("Bot: Python is a powerful and easy-to-learn programming language!")

        elif "jetson" in user_input:
            print("Bot: NVIDIA Jetson is a series of embedded AI computing boards.")

        elif "ai" in user_input:
            print("Bot: AI stands for Artificial Intelligence — machines that can learn and make decisions.")

        elif "name" in user_input:
            print("Bot: My name is KeywordBot. What's yours?")

        else:
            print("Bot: Sorry, I don't understand. Try asking about: hello, python, jetson, ai, or name.")


# ============================================================
# Main Menu
# ============================================================

def main() -> None:
    while True:
        print("\n" + "=" * 45)
        print("       Assignment One - Menu")
        print("=" * 45)
        print("1. Run Calculator")
        print("2. Run Interactive Keyword Bot")
        print("3. Exit")
        print("=" * 45)

        choice = input("Enter your choice (1/2/3): ").strip()

        if choice == "1":
            run_calculator()
        elif choice == "2":
            run_bot()
        elif choice == "3":
            print("\nGoodbye! Thank you for using the program.")
            break
        else:
            print("Invalid choice. Please enter 1, 2, or 3.")


if __name__ == "__main__":
    main()